Repository HongikComputerClub/gift-backend, pull requests merged in 2025-02, with the labels that each got.

#39 Docs #23 : API 명세서 작성
  .gitignore
  .gradle/8.11.1/checksums/checksums.lock
  .gradle/8.11.1/checksums/md5-checksums.bin
  .gradle/8.11.1/checksums/sha1-checksums.bin
  .gradle/8.11.1/executionHistory/executionHistory.bin
  .gradle/8.11.1/executionHistory/executionHistory.lock
  .gradle/8.11.1/fileHashes/fileHashes.bin
  .gradle/8.11.1/fileHashes/fileHashes.lock
  .gradle/8.11.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  OpenAI_call.py
  build.gradle
  src/main/java/com/team4/giftidea/controller/GptController.java
  src/main/java/com/team4/giftidea/repository/ProductRepository.java
  src/main/java/com/team4/giftidea/service/ProductService.java
  src/main/resources/application-prod.yml
Labels: ✨ feature, 📡 API, 📑 docs, ⚙️ setting

#40 feat #33 : Github Actions 도입 전 최종 설정
  .gitignore
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 🛠️ chore, ⚙️ setting

#41 Feature #33 : Github Actions CI 도입
  .github/workflows/ develop-ci.yml
Labels: ✨ feature, ⚙️ setting

#42 Feature #25 : 채팅 전처리 코드 자바로 변환
  src/main/java/com/team4/giftidea/controller/GptController.java
Labels: ✨ feature, 📁 data, ♻️ Refactor, 📡 API, 🛠️ chore

#43 Document #23 : Swagger 태그 추가 및 상세 설명 제공
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  src/main/java/com/team4/giftidea/controller/GptController.java
Labels: ✨ feature, 📡 API, 🛠️ chore

#47 feat #32 : SecurityConfig 추가
  .github/workflows/develop-ci.yml
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/com/team4/giftidea/configuration/SecurityConfig.java
  src/main/java/com/team4/giftidea/controller/GptController.java
Labels: ✨ feature, 📡 API

#63 fix #62 : 상품 저장 로직 개선 및 중복 처리 문제 해결
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  src/main/java/com/team4/giftidea/controller/ProductController.java
  src/main/java/com/team4/giftidea/repository/ProductRepository.java
  src/main/java/com/team4/giftidea/service/CoupangApiService.java
  src/main/java/com/team4/giftidea/service/KreamApiService.java
  src/main/java/com/team4/giftidea/service/ProductService.java
  team4_dump.sql
Labels: 🐛 fix

#70 Feature #69 : Proxy 서버 추가
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  src/main/java/com/team4/giftidea/controller/ProxyController.java
Labels: 🚨 Hotfix, ✨ feature, 📡 API, ⚙️ setting

#72 feat #32 : 허용 출처 설정 및 CORS Preflight 문제 해결
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  src/main/java/com/team4/giftidea/configuration/SecurityConfig.java
Labels: 🐛 fix, 📡 API

#74 feat #32 : 허용 출처 설정 및 CORS Preflight 문제 해결_local 주소 추가
  src/main/java/com/team4/giftidea/configuration/SecurityConfig.java
Labels: 🛠️ chore

#78 Feature/#78 : 추천 근거 필드 추가 및 근거 반환 기능 추가
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  src/main/java/com/team4/giftidea/controller/GptController.java
  src/main/java/com/team4/giftidea/entity/Product.java
Labels: 📁 data, 📡 API

#87 Feature/limit tokens
  .gradle/buildOutputCleanup/outputFiles.bin
  src/main/java/com/team4/giftidea/controller/GptController.java
  src/main/java/com/team4/giftidea/dto/GptRequestDTO.java
Labels: ✨ feature, 📡 API
